// ============================================
// SERVER.JS - Main Backend Server
// ============================================

require('dotenv').config();
const express = require('express');
const cors = require('cors');
const multer = require('multer');
const rateLimit = require('express-rate-limit');
const { createClient } = require('@supabase/supabase-js');
const mammoth = require('mammoth');
const pdfParse = require('pdf-parse');
const officeParser = require('officeparser');
const { YoutubeTranscript } = require('youtube-transcript');
const axios = require('axios');
const https = require('https');
const crypto = require('crypto');

// ============================================
// CONFIGURATION
// ============================================
const app = express();
const PORT = process.env.PORT || 3000;
let aiRequestCount = 0;

// Supabase Admin Client
const supabaseAdmin = createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_SERVICE_ROLE,
    {
        auth: {
            autoRefreshToken: false,
            persistSession: false
        },
        global: {
            fetch: (url, options = {}) => {
                return fetch(url, {
                    ...options,
                    agent: new https.Agent({ keepAlive: true, timeout: 30000 }),
                    timeout: 30000
                });
            }
        }
    }
);

// Gemini AI Configuration
const API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1/models/gemini-2.5-flash:generateContent?key=${API_KEY}`;

// ============================================
// MIDDLEWARE
// ============================================
app.use(cors());
app.use(express.json({
    limit: '10mb',
    verify: (req, res, buf) => {
        if (req.originalUrl === '/api/paystack-webhook') {
            req.rawBody = buf.toString();
        }
    }
}));
app.use(express.static('.'));

// Rate Limiter
const apiLimiter = rateLimit({
    windowMs: 5 * 60 * 1000,
    max: 100,
    standardHeaders: true,
    legacyHeaders: false,
    message: {
        success: false,
        error: "Too many requests. Please wait a few minutes."
    }
});
app.use("/api/", apiLimiter);

// File Upload Configuration
const storage = multer.memoryStorage();
const upload = multer({
    storage: storage,
    limits: { fileSize: 10 * 1024 * 1024 }
});

// ============================================
// GEMINI AI HELPER
// ============================================
async function generateWithGemini(promptText) {
    aiRequestCount++;
    console.log(`🤖 AI Request #${aiRequestCount} - Length: ${promptText.length}`);

    const payload = {
        contents: [
            {
                role: "user",
                parts: [{ text: promptText }]
            }
        ]
    };

    const controller = new AbortController();
    const timeout = setTimeout(() => controller.abort(), 30000);

    try {
        const response = await fetch(GEMINI_URL, {
            method: "POST",
            headers: { "Content-Type": "application/json" },
            body: JSON.stringify(payload),
            signal: controller.signal
        });

        clearTimeout(timeout);

        if (!response.ok) {
            const errData = await response.text();
            throw new Error(`Gemini API error (${response.status}): ${errData.substring(0, 200)}`);
        }

        const data = await response.json();
        const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!resultText) {
            throw new Error("No text generated by AI.");
        }

        return resultText;

    } catch (error) {
        if (error.name === "AbortError") {
            throw new Error("AI request timed out after 30 seconds.");
        }
        throw error;
    }
}

// ============================================
// AUTH MIDDLEWARE
// ============================================
async function requireAuth(req, res, next) {
    const authHeader = req.headers.authorization;
    if (!authHeader) {
        return res.status(401).json({ success: false, error: "No authorization header" });
    }

    const token = authHeader.replace("Bearer ", "");
    const { data, error } = await supabaseAdmin.auth.getUser(token);

    if (error || !data.user) {
        return res.status(401).json({ success: false, error: "Invalid or expired token" });
    }

    req.user = data.user;
    next();
}

// ============================================
// PRICING FUNCTIONS - FIXED NIGERIAN PRICING
// ============================================
function getPricingByCountry(country) {
    const normalized = country?.toUpperCase();

    const pricingMap = {
        // NIGERIA - Paystack (NGN) - FIXED: ₦3,500 = 350,000 kobo
        NG: { price: 350000, currency: "NGN", processor: "paystack" },
        
        // INTERNATIONAL - Flutterwave
        US: { price: 899, currency: "USD", processor: "flutterwave" },
        GB: { price: 799, currency: "GBP", processor: "flutterwave" },
        CA: { price: 1199, currency: "CAD", processor: "flutterwave" },
        DE: { price: 800, currency: "EUR", processor: "flutterwave" },
        FR: { price: 800, currency: "EUR", processor: "flutterwave" },
        IT: { price: 800, currency: "EUR", processor: "flutterwave" },
        ES: { price: 800, currency: "EUR", processor: "flutterwave" },
        NL: { price: 800, currency: "EUR", processor: "flutterwave" }
    };

    const selected = pricingMap[normalized] || pricingMap["US"];
    return {
        amount: selected.price,
        currency: selected.currency,
        processor: selected.processor
    };
}

// ============================================
// USAGE LIMIT FUNCTIONS
// ============================================
async function checkUsageLimit(userId) {
    const today = new Date();
    today.setHours(0, 0, 0, 0);

    const { data, error } = await supabaseAdmin
        .from('ai_usage')
        .select('id')
        .eq('user_id', userId)
        .gte('created_at', today.toISOString());

    if (error) {
        console.error("Usage check error:", error);
        throw new Error("Usage check failed");
    }
    return data.length;
}

async function logUsage(userId, type) {
    try {
        const { error } = await supabaseAdmin
            .from('ai_usage')
            .insert([{ user_id: userId, request_type: type }]);

        if (error) {
            console.error("Usage log error:", error.message);
        }
    } catch (err) {
        console.error("Usage log exception:", err.message);
    }
}

// ============================================
// FLUTTERWAVE PAYMENT INITIALIZATION
// ============================================
async function initializeFlutterwavePayment(user, amount, currency, billingMode) {
    try {
        const txRef = `SF-${Date.now()}-${Math.random().toString(36).substring(7)}`;

        const payload = {
            tx_ref: txRef,
            amount: amount / 100,
            currency: currency,
            redirect_url: `${process.env.APP_URL || 'http://localhost:3000'}/dashboard.html`,
            payment_options: "card",
            meta: {
                user_id: user.id,
                billing_mode: billingMode
            },
            customer: {
                email: user.email,
                name: user.user_metadata?.full_name || user.email.split('@')[0]
            },
            customizations: {
                title: "StudyForge AI Pro Plan",
                description: billingMode === "yearly" ? "Yearly Subscription" : "Monthly Subscription",
                logo: "https://studyforge.site/logo.png"
            }
        };

        const response = await axios.post(
            "https://api.flutterwave.com/v3/payments",
            payload,
            {
                headers: {
                    'Authorization': `Bearer ${process.env.FLUTTERWAVE_SECRET_KEY}`,
                    'Content-Type': 'application/json'
                }
            }
        );

        if (response.data.status === "success") {
            return {
                success: true,
                authorization_url: response.data.data.link,
                tx_ref: txRef
            };
        } else {
            return {
                success: false,
                error: "Flutterwave initialization failed"
            };
        }
    } catch (error) {
        console.error("Flutterwave init error:", error.response?.data || error.message);
        return {
            success: false,
            error: "Payment initialization failed"
        };
    }
}

// ============================================
// API ENDPOINTS
// ============================================

// Test endpoint
app.get('/api/test', (req, res) => {
    res.json({ status: "Server running", time: new Date().toISOString() });
});

// Condense study guide
app.post('/api/condense', requireAuth, async (req, res) => {
    try {
        const { content } = req.body;

        const usageCount = await checkUsageLimit(req.user.id);
        const { data: profile } = await supabaseAdmin
            .from('profiles')
            .select('plan, pro_expires_at')
            .eq('id', req.user.id)
            .single();

        const now = new Date();
        const isProActive = profile?.plan === "pro" && profile?.pro_expires_at && new Date(profile.pro_expires_at) > now;

        if (!isProActive && usageCount >= 5) {
            return res.status(403).json({ success: false, error: "Daily limit reached. Upgrade to Pro." });
        }

        if (!content) return res.status(400).json({ success: false, error: "No content provided" });
        if (content.length > 60000) return res.status(400).json({ success: false, error: "Content too long" });

        const prompt = `
You are a structured academic formatting engine. Format the content into clean, readable sections.

OUTPUT FORMAT RULES:
1. Use ONLY plain text - NO markdown symbols.
2. DO NOT use any special characters for formatting.
3. Section titles should be written as plain text without any symbols.
4. Use simple bullet points with dashes (-) only when listing items.

Create these exact sections in this order:

Executive Summary
[Write a 2-3 paragraph summary here]

Key Concepts Explained Simply
- Concept 1 explanation
- Concept 2 explanation
- Concept 3 explanation

Exam-Ready Bullet Points
- Important point 1
- Important point 2
- Important point 3

Practice Questions
- Question 1
- Question 2
- Question 3
- Question 4
- Question 5

Flashcards (Term - Definition)
Term 1 - Definition 1
Term 2 - Definition 2
Term 3 - Definition 3
Term 4 - Definition 4
Term 5 - Definition 5

Quick Revision Sheet
- Key takeaway 1
- Key takeaway 2
- Key takeaway 3

Now format this content exactly as specified above with NO symbols:

${content}
`;

        const resultText = await generateWithGemini(prompt);
        await logUsage(req.user.id, "condense");

        res.json({ success: true, data: resultText });

    } catch (error) {
        console.error("Condense Error:", error.message);
        res.status(500).json({ success: false, error: "Failed to condense content" });
    }
});

// Chat with AI
app.post('/api/chat', requireAuth, async (req, res) => {
    try {
        const { question, context } = req.body;

        const usageCount = await checkUsageLimit(req.user.id);
        const { data: profile } = await supabaseAdmin
            .from('profiles')
            .select('plan, pro_expires_at')
            .eq('id', req.user.id)
            .single();

        const now = new Date();
        const isProActive = profile?.plan === "pro" && profile?.pro_expires_at && new Date(profile.pro_expires_at) > now;

        if (!isProActive && usageCount >= 5) {
            return res.status(403).json({ success: false, error: "Daily limit reached. Upgrade to Pro." });
        }

        if (!question || !context) {
            return res.status(400).json({ success: false, error: "Missing question or context" });
        }

        const prompt = `
You are an academic tutor.

Rules:
- Plain text only
- No markdown
- No special formatting
- Use dash bullets only if user asks for list

Context:
${context}

Question:
${question}
`;

        const answer = await generateWithGemini(prompt);
        await logUsage(req.user.id, "chat");

        res.json({ success: true, data: answer || "I couldn't generate an answer." });

    } catch (error) {
        console.error("Chat Error:", error.message);
        res.status(500).json({ success: false, error: "Failed to generate chat response" });
    }
});

// Exam mode
app.post('/api/exam-mode', requireAuth, async (req, res) => {
    try {
        const { content } = req.body;

        const usageCount = await checkUsageLimit(req.user.id);
        const { data: profile } = await supabaseAdmin
            .from('profiles')
            .select('plan, pro_expires_at')
            .eq('id', req.user.id)
            .single();

        const now = new Date();
        const isProActive = profile?.plan === "pro" && profile?.pro_expires_at && new Date(profile.pro_expires_at) > now;

        if (!isProActive && usageCount >= 5) {
            return res.status(403).json({ success: false, error: "Daily limit reached. Upgrade to Pro." });
        }

        if (!content) return res.status(400).json({ success: false, error: "No content provided" });
        if (content.length > 20000) return res.status(400).json({ success: false, error: "Content too long" });

        const prompt = `
You are an academic exam-setting engine.

STRICT RULES:
- Plain text only
- No markdown
- No bold
- No tables

Output EXACTLY in this format:

Likely Theory Questions
- Question 1
- Question 2
- Question 3

Multiple Choice Questions
Question 1
A. Option
B. Option
C. Option
D. Option
Answer: Correct Letter

Marking Scheme
Question 1 - Model Answer
Question 2 - Model Answer

Content:
${content}
`;

        const resultText = await generateWithGemini(prompt);
        await logUsage(req.user.id, "exam");

        res.json({ success: true, data: resultText });

    } catch (error) {
        console.error("Exam Mode Error:", error.message);
        res.status(500).json({ success: false, error: "Failed to generate exam mode" });
    }
});

// File upload
app.post("/api/upload-file", requireAuth, upload.single("file"), async (req, res) => {
    try {
        if (!req.file) {
            return res.status(400).json({ error: "No file uploaded" });
        }

        const fileName = req.file.originalname.toLowerCase();
        let extractedText = "";

        if (fileName.endsWith(".pdf")) {
            const data = await pdfParse(req.file.buffer);
            extractedText = data.text;
        }
        else if (fileName.endsWith(".docx")) {
            const result = await mammoth.extractRawText({ buffer: req.file.buffer });
            extractedText = result.value;
        }
        else if (fileName.endsWith(".pptx")) {
            extractedText = await officeParser.parseOfficeAsync(req.file.buffer);
        }
        else {
            return res.status(400).json({ error: "Unsupported file type. Only .pdf, .docx and .pptx are supported" });
        }

        if (!extractedText || extractedText.trim().length === 0) {
            return res.status(422).json({ error: "No text could be extracted from the file" });
        }

        res.json({
            success: true,
            text: extractedText,
            length: extractedText.length
        });

    } catch (error) {
        console.error("File upload error:", error);
        res.status(500).json({ error: "Extraction failed", details: error.message });
    }
});

// ============================================
// INITIALIZE PAYMENT - WITH YEARLY LOGGING
// ============================================
app.post("/api/initialize-payment", requireAuth, async (req, res) => {
    try {
        const { country, billingMode } = req.body;

        if (!["monthly", "yearly"].includes(billingMode)) {
            return res.status(400).json({ success: false, error: "Invalid billing mode" });
        }

        if (!country) {
            return res.status(400).json({ success: false, error: "Country required" });
        }

        const pricing = getPricingByCountry(country);
        let finalAmount = pricing.amount;

        if (billingMode === "yearly") {
            finalAmount = Math.round(pricing.amount * 12 * 0.8);
            console.log("📅 Yearly pricing applied:", { original: pricing.amount, final: finalAmount });
        }

        const metadata = {
            user_id: req.user.id,
            billing_mode: billingMode,
            processor: pricing.processor,
            country: country
        };

        if (pricing.processor === "paystack") {
            console.log(`💰 Using Paystack for ${country}`);

            const response = await axios.post("https://api.paystack.co/transaction/initialize", {
                email: req.user.email,
                amount: finalAmount,
                currency: pricing.currency,
                metadata: metadata,
                callback_url: `${process.env.APP_URL || 'http://localhost:3000'}/dashboard.html`
            }, {
                headers: { Authorization: `Bearer ${process.env.PAYSTACK_SECRET}` }
            });

            if (!response.data.status) {
                return res.status(400).json({ success: false, error: "Payment initialization failed" });
            }

            return res.json({
                success: true,
                authorization_url: response.data.data.authorization_url,
                processor: "paystack"
            });

        } else {
            console.log(`💰 Using Flutterwave for ${country}`);

            const flutterwaveResult = await initializeFlutterwavePayment(
                req.user,
                finalAmount,
                pricing.currency,
                billingMode
            );

            if (!flutterwaveResult.success) {
                return res.status(400).json({
                    success: false,
                    error: flutterwaveResult.error
                });
            }

            metadata.flutterwave_tx_ref = flutterwaveResult.tx_ref;

            return res.json({
                success: true,
                authorization_url: flutterwaveResult.authorization_url,
                processor: "flutterwave"
            });
        }

    } catch (error) {
        console.error("Payment Init Error:", error.message);
        res.status(500).json({ success: false, error: "Payment initialization error" });
    }
});

// ============================================
// VERIFY PAYMENT
// ============================================
app.post('/api/verify-payment', requireAuth, async (req, res) => {
    try {
        const { reference, billingMode } = req.body;

        console.log(`🔍 Verifying payment: ${reference}, mode: ${billingMode}`);

        if (!reference) {
            return res.status(400).json({ success: false, error: "No reference provided" });
        }

        const response = await axios.get(`https://api.paystack.co/transaction/verify/${reference}`, {
            headers: {
                'Authorization': `Bearer ${process.env.PAYSTACK_SECRET}`,
                'Content-Type': 'application/json'
            }
        });

        const paymentData = response.data.data;

        if (paymentData.status !== "success") {
            return res.status(400).json({
                success: false,
                error: "Payment not successful",
                status: paymentData.status
            });
        }

        const { data: existing } = await supabaseAdmin
            .from('transactions')
            .select('id')
            .eq('reference', reference)
            .maybeSingle();

        if (existing) {
            return res.json({
                success: true,
                message: "Transaction already processed",
                alreadyPro: true
            });
        }

        const expiryDate = new Date();
        if (billingMode === "yearly") {
            expiryDate.setDate(expiryDate.getDate() + 365);
        } else {
            expiryDate.setDate(expiryDate.getDate() + 30);
        }

        await supabaseAdmin.from('transactions').insert([{
            user_id: req.user.id,
            reference: reference,
            amount: paymentData.amount,
            currency: paymentData.currency,
            status: "success",
            created_at: new Date().toISOString()
        }]);

        const { error: updateError } = await supabaseAdmin
            .from('profiles')
            .update({
                plan: "pro",
                pro_expires_at: expiryDate.toISOString()
            })
            .eq('id', req.user.id);

        if (updateError) {
            console.error('❌ Profile update error:', updateError);
            return res.status(500).json({
                success: false,
                error: "Failed to update profile"
            });
        }

        console.log(`✅ User ${req.user.id} upgraded to Pro until ${expiryDate.toDateString()}`);

        res.json({
            success: true,
            message: "Payment verified and account upgraded",
            plan: "pro",
            expires_at: expiryDate.toISOString()
        });

    } catch (err) {
        console.error("❌ Payment verification error:", err.message);
        res.status(500).json({
            success: false,
            error: "Payment verification failed",
            details: err.message
        });
    }
});

// ============================================
// STUDY GUIDES ENDPOINTS
// ============================================
app.post('/api/save-guide', requireAuth, async (req, res) => {
    try {
        const { title, content } = req.body;

        if (!content) {
            return res.status(400).json({ success: false, error: "Content is required" });
        }

        const { error } = await supabaseAdmin
            .from('study_guides')
            .insert({
                user_id: req.user.id,
                title: title || "Untitled Guide",
                content: content
            });

        if (error) throw error;

        res.json({ success: true });

    } catch (err) {
        res.status(500).json({ success: false, error: "Failed to save guide" });
    }
});

app.get('/api/my-guides', requireAuth, async (req, res) => {
    try {
        const { data, error } = await supabaseAdmin
            .from('study_guides')
            .select('*')
            .eq('user_id', req.user.id)
            .order('created_at', { ascending: false });

        if (error) throw error;

        res.json({ success: true, guides: data });

    } catch (err) {
        res.status(500).json({ success: false, error: "Failed to fetch guides" });
    }
});

app.delete('/api/delete-guide/:id', requireAuth, async (req, res) => {
    try {
        const { id } = req.params;

        const { error } = await supabaseAdmin
            .from('study_guides')
            .delete()
            .eq('id', id)
            .eq('user_id', req.user.id);

        if (error) throw error;

        res.json({ success: true });

    } catch (err) {
        res.status(500).json({ success: false, error: "Delete failed" });
    }
});

// ============================================
// USAGE AND ACCOUNT ENDPOINTS
// ============================================
app.get('/api/usage', requireAuth, async (req, res) => {
    try {
        const usageCount = await checkUsageLimit(req.user.id);
        res.json({ success: true, used: usageCount, limit: 5 });
    } catch (error) {
        res.status(500).json({ success: false, error: "Failed to fetch usage" });
    }
});

app.get('/api/account', requireAuth, async (req, res) => {
    try {
        const { data, error } = await supabaseAdmin
            .from('profiles')
            .select('plan, pro_expires_at')
            .eq('id', req.user.id)
            .maybeSingle();

        if (error) {
            return res.json({ success: true, plan: 'free', expires_at: null });
        }

        if (!data) {
            await supabaseAdmin
                .from('profiles')
                .insert({ id: req.user.id, plan: 'free', created_at: new Date().toISOString() });

            return res.json({ success: true, plan: 'free', expires_at: null });
        }

        res.json({ success: true, plan: data.plan || "free", expires_at: data.pro_expires_at || null });

    } catch (err) {
        res.json({ success: true, plan: 'free', expires_at: null });
    }
});

// ============================================
// YOUTUBE TRANSCRIPT
// ============================================
app.post('/api/youtube-transcript', async (req, res) => {
    try {
        const { url } = req.body;
        if (!url) return res.status(400).json({ error: "No URL provided" });

        const transcript = await YoutubeTranscript.fetchTranscript(url);
        const text = transcript.map(item => item.text).join(' ');

        res.json({ success: true, text });

    } catch (error) {
        res.status(500).json({ error: "Transcript failed", details: error.message });
    }
});

// ============================================
// WEBHOOKS
// ============================================
app.post('/api/paystack-webhook', async (req, res) => {
    try {
        const hash = crypto
            .createHmac('sha512', process.env.PAYSTACK_SECRET)
            .update(req.rawBody)
            .digest('hex');

        if (hash !== req.headers['x-paystack-signature']) {
            console.log("❌ Invalid Paystack signature");
            return res.sendStatus(401);
        }

        const event = req.body;

        if (event.event === "charge.success") {
            const data = event.data;
            const reference = data.reference;
            const userId = data.metadata?.user_id;

            if (!userId) return res.sendStatus(200);

            const { data: existing } = await supabaseAdmin
                .from('transactions')
                .select('id')
                .eq('reference', reference)
                .maybeSingle();

            if (existing) return res.sendStatus(200);

            const expiryDate = new Date();
            const billingMode = data.metadata?.billing_mode;

            if (billingMode === "yearly") {
                expiryDate.setDate(expiryDate.getDate() + 365);
            } else {
                expiryDate.setDate(expiryDate.getDate() + 30);
            }

            await supabaseAdmin.from('transactions').insert([{
                user_id: userId,
                reference: reference,
                amount: data.amount,
                currency: data.currency,
                status: "success",
                created_at: new Date().toISOString()
            }]);

            await supabaseAdmin.from('profiles').update({
                plan: "pro",
                pro_expires_at: expiryDate.toISOString()
            }).eq('id', userId);

            console.log(`✅ Webhook upgraded user ${userId}`);
        }

        res.sendStatus(200);

    } catch (err) {
        console.error("Webhook error:", err.message);
        res.sendStatus(500);
    }
});

app.post('/api/flutterwave-webhook', async (req, res) => {
    try {
        const secretHash = process.env.FLUTTERWAVE_SECRET_HASH || "studyforge_secret";
        const signature = req.headers['verif-hash'];

        if (!signature || signature !== secretHash) {
            console.log("❌ Invalid Flutterwave signature");
            return res.sendStatus(401);
        }

        const event = req.body;

        if (event.event === "charge.completed" && event.data.status === "successful") {
            const data = event.data;
            const txRef = data.tx_ref;
            const userId = data.meta?.user_id;
            const billingMode = data.meta?.billing_mode;

            if (!userId) return res.sendStatus(200);

            const { data: existing } = await supabaseAdmin
                .from('transactions')
                .select('id')
                .eq('reference', txRef)
                .maybeSingle();

            if (existing) return res.sendStatus(200);

            const expiryDate = new Date();
            if (billingMode === "yearly") {
                expiryDate.setDate(expiryDate.getDate() + 365);
            } else {
                expiryDate.setDate(expiryDate.getDate() + 30);
            }

            await supabaseAdmin.from('transactions').insert([{
                user_id: userId,
                reference: txRef,
                amount: data.amount * 100,
                currency: data.currency,
                status: "success",
                processor: "flutterwave",
                created_at: new Date().toISOString()
            }]);

            await supabaseAdmin.from('profiles').update({
                plan: "pro",
                pro_expires_at: expiryDate.toISOString()
            }).eq('id', userId);

            console.log(`✅ Flutterwave webhook upgraded user ${userId}`);
        }

        res.sendStatus(200);

    } catch (err) {
        console.error("Flutterwave webhook error:", err.message);
        res.sendStatus(500);
    }
});

// ============================================
// HEALTH CHECK ENDPOINT - Add this anywhere in server.js
// ============================================
app.get('/api/health', (req, res) => {
    res.status(200).json({ 
        status: 'alive', 
        time: new Date().toISOString(),
        uptime: process.uptime()
    });
});

// ============================================
// START SERVER
// ============================================
app.listen(PORT, () => {
    console.log(`🚀 StudyForge AI Server running on http://localhost:${PORT}`);
    console.log(`📝 Environment: Node ${process.version}`);
});