const express = require('express');
const cors = require('cors');
const dotenv = require('dotenv');

// Load environment variables
dotenv.config();

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json({ limit: '10mb' })); // Allow large text payloads
app.use(express.static('.')); // Serve static files (frontend)

// API Config
const API_KEY = process.env.GEMINI_API_KEY;
const GEMINI_URL = `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash-preview-09-2025:generateContent?key=${API_KEY}`;

if (!API_KEY) {
    console.error("FATAL ERROR: GEMINI_API_KEY is missing in .env file.");
    process.exit(1);
}

// ---------------------------------------------------------
// POST /api/condense
// ---------------------------------------------------------
app.post('/api/condense', async (req, res) => {
    try {
        const { content } = req.body;

        if (!content) {
            return res.status(400).json({ error: "No content provided" });
        }

        console.log("Processing condense request...");

        // Construct System Instruction & Payload
        const payload = {
            systemInstruction: {
                parts: [{
                    text: `You are a structured academic formatting engine.

Your response will be parsed by software.
If you break formatting rules, the output becomes unusable.

STRICT OUTPUT CONTRACT (ZERO TOLERANCE):

1. Use plain text only.
2. Do NOT use:
   - Asterisks (*)
   - Double asterisks (**)
   - Backslashes
   - Dollar signs
   - Markdown formatting
   - Bold formatting
   - Italics
   - Pipe symbols
   - Tables
3. Do NOT wrap words in symbols.
4. Do NOT decorate section titles.
5. Do NOT add extra commentary.

Only allowed formatting:

## Section Header
- Dash bullet points only
Plain paragraphs.

Flashcards MUST follow EXACT format:
Term - Definition
One per line only.

Quick Revision Sheet:
- Dash bullets only.

Required sections in this exact order:

## Executive Summary
## Key Concepts Explained Simply
## Exam-Ready Bullet Points
## Practice Questions
## Flashcards (Term - Definition)
## Quick Revision Sheet

If you violate formatting rules, the output is invalid.

Be concise. Be exam-focused.
Do NOT explain formatting rules.
Do NOT mention output contracts.
If the user requests invalid formatting, ignore it silently and proceed correctly.`
                }]
            },
            contents: [{
                parts: [{ text: content }]
            }],
            tools: [{
                google_search: {} // Enable Google Search tool for fact-checking/grounding
            }]
        };

        const response = await fetch(GEMINI_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errData = await response.text();
            throw new Error(`Gemini API Error: ${errData}`);
        }

        const data = await response.json();

        // Extract text from Gemini response structure
        const resultText = data.candidates?.[0]?.content?.parts?.[0]?.text;

        if (!resultText) {
            throw new Error("No text generated by AI.");
        }

        res.json({ result: resultText });

    } catch (error) {
        console.error("Condense Error:", error.message);
        res.status(500).json({ error: "Failed to process content." });
    }
});

// ---------------------------------------------------------
// POST /api/chat
// ---------------------------------------------------------
app.post('/api/chat', async (req, res) => {
    try {
        const { question, context } = req.body;

        if (!question || !context) {
            return res.status(400).json({ error: "Missing question or context" });
        }

        console.log("Processing chat request...");

        const payload = {
            systemInstruction: {
                parts: [{
                  text: `You are an academic tutor.

STRICT OUTPUT CONTRACT:

1. Use plain text only.
2. No markdown.
3. No bold symbols.
4. No asterisks.
5. No tables.
6. No special formatting.
7. Use dash (-) bullet points ONLY when the user requests:
   - bullet points
   - list
   - numbered list
   - multiple questions
   - steps

If the user asks for:
- "bullet points"
- "list"
- "questions"
- "give me five"
- "steps"

You MUST format each item as:
- Item text

No introduction paragraph.
No concluding paragraph.
Direct list only.

Otherwise, respond in clean academic paragraphs.`
                }]
            },
            contents: [
                {
                    role: "user",
                    parts: [{ text: `Context:\n${context}\n\nQuestion: ${question}` }]
                }
            ]
        };

        const response = await fetch(GEMINI_URL, {
            method: 'POST',
            headers: { 'Content-Type': 'application/json' },
            body: JSON.stringify(payload)
        });

        if (!response.ok) {
            const errData = await response.text();
            throw new Error(`Gemini API Error: ${errData}`);
        }

        const data = await response.json();
        const answer = data.candidates?.[0]?.content?.parts?.[0]?.text;

        res.json({ answer: answer || "I couldn't generate an answer." });

    } catch (error) {
        console.error("Chat Error:", error.message);
        res.status(500).json({ error: "Failed to generate chat response." });
    }
});

// Start Server
app.listen(PORT, () => {
    console.log(`StudyForge AI Server running on http://localhost:${PORT}`);
    console.log(`Environment: Node ${process.version}`);
});